:doctype: article

:!toc:
//:linkcss:
:imagesdir: images/
:stylesdir: stylesheets/
:stylesheet: monospace.css
:docinfo:
:last-update-label!:
:nofooter:
:linkattrs:


= Stefan Sitani

//+420 775 169 615 +
//He/Him
ssitani@redhat.com +
IRC: ssitani +
GitHub: link:https://github.com/inoxx03[inoxx03^] +
Brno, Czech Republic
//stefan.sitani@gmail.com
//TODO: Add image icons with hyperlinks to GH, Internal GL, Rover, Linkedin, etc.

== Objectives

As an Associate Content Strategist for Red{nbsp}Hat build of Quarkus, I can offer 5 years of experience in writing documentation for Red{nbsp}Hat products, including 10 months of experience that I have gained in my current role Senior Technical Writer with Red{nbsp}Hat build of Quarkus.

With my current product experience and above-average relationships with stakeholders on the product and community sides of Quarkus, I believe that I would be at an advantageous position to resolves some of the specific issues concerning collaboration and unity of content between the product and the project documentation sets.

Moreover, in my time of working on product documentation for Quarkus, I have actively engaged in building and managing relationships with community and product stakeholders. In collaboration with the team of writers on Red{nbsp}Hat Build of Quarkus, I have produced and published release notes for multiple minor and patch releases of the product, and regularly maintained published guides to ensure that they remain compliant with the Customer Content Services' standards for Flexible Customer content structuring and technical accuracy. I am currently representing CCS in the collaboration between the Quarkus community and Red{nbsp}Hat with the goal of redesigning the way we present Quarkus to community users an Red{nbsp}Hat customers. In this role I am also participating in making low- and mid-level strategic decisions about our content under the guidance of our Senior Content strategist.

In my new role as Associate Content Strategist, I offer to represent Customer Content Services and our team of Red{nbsp}Hat Technical Writers in negotiations and strategic decision-making processes with the aim of improving the collaboration between project and product stakeholders and safeguarding the shared interest of delivering technically accurate usable and re-usable content that can be efficiently maintained an is fully compatible with Red{nbsp}Hat's new content management and publishing tools.

== Technical Writing Experience

=== Red{nbsp}Hat
//.Brno, Czech Republic

*Senior Technical Writer*

.Red{nbsp}Hat build of Quarkus (RHBQ)
_since November 2020_

* Collaborate with Engineering and Quality Engineering stakeholders to address issues related to the technical accuracy of the documentation
* Compile and publish release notes for 2 minor and 3 patch releases of RHBQ
* Collaborate with a team of 3 Technical Writers, a Documentation Program Manager, and a Senior Content Strategist to:
** Write documentation according to Flexible Customer Content guidelines
** Plan the delivery of documentation content for new releases of RHBQ
** Verify and update published documentation content to match the development of the community project
** Prepare documentation content for migration to Pantheon V2
* Work according to Agile methodology based on SCRUM
* Participate in coaching and onboarding a new team member

*Senior Technical Writer*

.Red{nbsp}Hat Cloud-Native Runtimes (CNR)
_October 2019 - October 2020_


* Write, maintain, and publish the Documentation for Red{nbsp}Hat support for Spring Boot
* Write documentation according to Flexible Customer Content guidelines
* Collaborate with Documentation Program Manager and Content Strategist to:
** Plan the delivery of documentation content for new features on Spring Boot
** Synchronize documentation changes across multiple runtimes
** Address issues that involve coordinating documentation development across different Middleware products
**  Maintain the CNRDOC project in JIRA
* Implement a Git-based content sharing workflow for reusing content between documentation repositories.

*Technical Writer*

.Red{nbsp}Hat OpenShift Application Runtimes (RHOAR)
_June 2018 - September 2019_


* Maintain Community documentation for Application Development on OpenShift and Fabric8 Launcher
* Document the use of Minishift with RHOAR
* Write documentation according to Flexible Customer Content guidelines
* Document creating a basic application from scratch with RHOAR and deploying it to different version of OpenShift
* Document the use of Fabric8 Launcher for deploying RHOAR example applications to OpenShift and stand-alone RHEL
* Collaborate with the Documentation Program Manager to deliver documentation for new features on a highly flexible release plan.
* Collaborate with engineering and QE teams developing Spring Boot, Eclipse vert.x, Thorntail and Node.js on documenting recommended practices for developing with RHOAR.
//* Reorganize the repository structure and re-brand the documentation to CNR.

*Associate Technical Writer*

.Red{nbsp}Hat OpenShift Application Runtimes (RHOAR)
_Feb 2017 - May 2018_


* Maintain Community documentation for application development with OpenShift and Fabric8 Launcher.
* Share content between community documentation and product documentation on the Red{nbsp}Hat Customer Portal.
* Write procedures for using example applications based on Spring Boot, Thorntail and Eclipse Vert.x, and Node.js.
* Write documentation for deploying applications using the Fabric8 Maven Plugin
* Collaborate with the Principal Writer in creating the documentation set for a new Red{nbsp}Hat Middleware product.
* Create and maintain release notes for all Red{nbsp}Hat OpenShift Application Runtimes


*Technical Writer Intern*

.Red{nbsp}Hat Mobile Application Platform
_May 2016 - January 2017_ +

* Maintain documentation for Red{nbsp}Hat Mobile application platform
* Perform maintenance tasks and minor enhancements to documentation
* Convert community documentation in Markdown to AsciiDoc for publishing on the Red{nbsp}Hat Customer Portal
* Align the delivery of documentation updates with he SCRUM development cycle of the product

== Other Published Content

.Red{nbsp}Hat Supplementary Style Guide

_first published August 2020 with regular monthly updates_

* Wrote section on using AsciiDoc attributes for substituting product names and versions
* Added other smaller contributions and updates to various chapters of the guide
* Periodcally serve as the repository administrator for the guide on a rotating schedule
* Co-leading the initiative in collaboration with Andrea Hoffer

.AsciiDoc Tutorial

_published May 2017_

* Created in collaboration with Jiri Herrmann
* Part 1 covers basic recommended practices for writing content in AsciiDoc
* An example documentation repository where newly hired writers can practice writing content with AsciiDoc and building it using Red{nbsp}Hat and community-based tools.

.AsciiDoc Tutorial, Part 2

_published September 2018_

* Created in collaboration with Jiri Herrmann
* Part 2 covers intermediate-level practices for writing content in AsciiDoc
* An example documentation repository where writers can practice structuring documentation titles, including and reusing parts of content, and defining conditionals to filter content between community and product documentation sets.


== Other Activities

.Middleware Documentation Hackathon

_since April 2020_

* Organize writers from products in Middleware Runtimes to restructure product documentation according to Flexible Customer Content guidelines
* Work with documentation project owners within Red{nbsp}Hat and in communities outside of Red{nbsp}Hat to plan the restructuring effort and align it with the specific contribution guidelines of each project.

.Maintaining Documentation for Red{nbsp}Hat Migration Tool for Applications

_intermittently between February 2019 - January 2020_

* Temporary technical writer position on RHMTA, working on an as-needed basis
* Update, maintain, and publish product documentation and release notes for the RHAMT 4.2.1, 4.3.0, and 4.3.1
* Single-source documentation changes between the WINDUP community project and the RHMTA product documentation

<<<

== Languages and Tools

Markup languages::
** AsciiDoc, Markdown, DocBook 5, HTML

Publishing tools::
** Red{nbsp}Hat Pantheon, AsciiDoctor, GitHub Pages, Errata Tool, Customer Portal

Issue Tracking Tools::
** JIRA, Bugzilla

Developer Tools & Platforms::
** Maven, MiniShift, CodeReady Containers, Openshift 3.x, Red{nbsp}Hat Enterprise Linux 7, `oc`
