:doctype: article

== Stefan Sitani

:!toc:
//:linkcss:
:imagesdir: images/
:stylesdir: css/
:stylesheet: print.css

//+420 775 169 615 +
ssitani@redhat.com +
IRC: ssitani +
Brno, Czech Republic
//stefan.sitani@gmail.com

== Objectives

As a Senior Technical Writer on Quarkus documentation, I can offer 4 years of experience that I have gained as the co-author and maintainer of the documentation for Red Hat Cloud-Native Runtimes (formerly designated as Red Hat OpenShift Application Runtimes).
//I am proficient in writing developer-oriented documentation content for creating Java-based and, to a lesser extent, JavaScript-based applications for deployment in OpenShift and Kubernetes.
//I am also comfortable working with Maven, OpenJDK, CodeReady Studio, Minishift and Container Development Kit/CodeReady Containers and have experience with OpenShift both in the Web Console and using the `oc` (and to a lesser extent ODO) command-line tool.
I have worked as a sole writer and maintainer of a documentation project, and also as part of a team where I collaborate with stakeholders from Customer Content Services and also from other functional areas of Red Hat PnT to make low- and medium-level strategic decisions to develop our documentation according to the current needs of the customers.

//to further improve my knowledge of enterprise Java frameworks for cloud-native application development, focusing on the more recent and emerging technologies that are part of the ecosystem (such as GraalVM and OpenShift 4)
In my new role, I aim to apply my current knowledge to write high-quality documentation content on advanced developer-oriented topics and to collaborate with other writers and stakeholders within and outside of Red Hat Middleware Runtimes to tackle documentation planning and content strategy-related decisions.
I consider the recent shift of strategic focus at Red Hat towards providing managed services for the Open Hybrid Cloud as a particularly interesting challenge to navigate while working on documenting a dynamic and innovative product that Quarkus is.

== Technical Writing Experience

=== Red Hat
//.Brno, Czech Republic

*Senior Technical Writer*

.Red Hat Cloud-Native Runtimes (CNR)
_since October 2019_


* Write, maintain, and publish the Documentation for Red Hat support for Spring Boot
* Write documentation according to Flexible Customer Content guidelines
* Collaborate with Documentation Program Manager and Content Strategist to:
** Plan the delivery of documentation content for new features on Spring Boot
** Synchronize documentation changes across multiple runtimes
** Address issues that involve coordinating documentation development across different Middleware products
**  Maintain the CNRDOC project in JIRA
* Implement a Git-based content sharing workflow for reusing content between documentation repositories.

*Technical Writer*

.Red Hat OpenShift Application Runtimes (RHOAR)
_June 2018 - September 2019_


* Maintain Community documentation for Application Development on OpenShift and Fabric8 Launcher
* Document the use of Minishift with RHOAR
* Write documentation according to Flexible Customer Content guidelines
* Document creating a basic application from scratch with RHOAR and deploying it to different version of OpenShift
* Document the use of Fabric8 Launcher for deploying RHOAR example applications to OpenShift and stand-alone RHEL
* Collaborate with the Documentation Program Manager to deliver documentation for new features on a highly flexible release plan.
* Collaborate with engineering and QE teams developing Spring Boot, Eclipse vert.x, Thorntail and Node.js on documenting recommended practices for developing with RHOAR.
//* Reorganize the repository structure and re-brand the documentation to CNR.

*Associate Technical Writer*

.Red Hat OpenShift Application Runtimes (RHOAR)
_Feb 2017 - May 2018_


* Maintain Community documentation for application development with OpenShift and Fabric8 Launcher.
* Share content between community documentation and product documentation on the Red Hat Customer Portal.
* Write procedures for using example applications based on Spring Boot, Thorntail and Eclipse Vert.x, and Node.js.
* Write documentation for deploying applications using the Fabric8 Maven Plugin
* Collaborate with the Principal Writer in creating the documentation set for a new Red Hat Middleware product.
* Create and maintain release notes for all Red Hat OpenShift Application Runtimes


*Technical Writer Intern*

.Red Hat Mobile Application Platform
_May 2016 - January 2017_ +


* Maintain documentation for Red Hat Mobile application platform
* Perform maintenance tasks and minor enhancements to documentation
* Convert community documentation in Markdown to AsciiDoc for publishing on the Red Hat Customer Portal
* Align the delivery of documentation updates with he SCRUM development cycle of the product

= Other Published Content

.AsciiDoc Tutorial

_published May 2017_

* Created in collaboration with Jiri Herrmann
* Part 1 covers basic recommended practices for writing content in AsciiDoc
* An example documentation repository where newly hired writers can practice writing content with AsciiDoc and building it using Red Hat and community-based tools.

.AsciiDoc Tutorial, Part 2

_published September 2018_

* Created in collaboration with Jiri Herrmann
* Part 2 covers intermediate-level practices for writing content in AsciiDoc
* An example documentation repository where writers can practice structuring documentation titles, including and reusing parts of content, and defining conditionals to filter content between community and product documentation sets.


== Other Activities

.Middleware Documentation Hackathon

_since April 2020_

* Organize writers from products in Middleware Runtimes to restructure product documentation according to Flexible Customer Content guidelines
* Work with documentation project owners within Red Hat and in communities outside of Red Hat to plan the restructuring effort and align it with the specific contribution guidelines of each project.

.Maintaining Documentation for Red Hat Migration Tool for Applications

_intermittently between February 2019 - January 2020_

* Temporary technical writer position on RHMTA, working on an as-needed basis
* Update, maintain, and publish product documentation and release notes for the RHAMT 4.2.1, 4.3.0 and 4.3.1
* Single-source documentation changes between the WINDUP community project and the RHMTA product documentation

<<<

== Languages and Tools

Markup languages::
** AsciiDoc, Markdown, DocBook 5, HTML

Publishing tools::
** Red Hat Pantheon, AsciiDoctor, GitHub Pages, Errata Tool, Customer Portal

Issue Tracking Tools::
** JIRA, Bugzilla

Developer Tools & Platforms::
** Maven, MiniShift, CodeReady Containers, Openshift 3.x, Red Hat Enterprise Linux 7, `oc`
